controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    omni_drive_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_lift
      - joint_wrist_yaw
      - joint_wrist_pitch
      - joint_wrist_roll
      - joint_gripper_slide
      - joint_head_pan
      - joint_head_tilt
    open_loop_control: true

joint_velocity_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_lift
      - joint_wrist_pitch
      - joint_wrist_roll
      - joint_wrist_yaw
      - joint_head_pan
      - joint_head_tilt
      - joint_gripper_slide

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["joint_left_wheel"]
    right_wheel_names: ["joint_right_wheel"]
    wheel_separation: 0.3
    wheels_per_side: 1
    wheel_radius: 0.05
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    open_loop: true
    enable_odom_tf: true
    use_stamped_vel: true
    cmd_vel_timeout: 0.5

    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 0.42
        max_acceleration: 0.2
        max_jerk: 0.0

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 0.42
        max_acceleration: 0.2
        max_jerk: 0.0

omni_drive_controller:
  ros__parameters:
    wheel_offset: 0.0
    wheel_names:
      [
        "joint_left_wheel",
        "joint_right_wheel",
      ]

    robot_radius: 0.20
    wheel_radius: 0.02

    odom_frame_id: odom
    base_frame_id: base_link


    open_loop: true
    position_feedback: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true