controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint_lift
      - joint_wrist_yaw
      - joint_wrist_pitch
      - joint_wrist_roll
      - joint_gripper_slide
      - joint_head_pan
      - joint_head_tilt

    command_interfaces:
      - position
      # - velocity
      # - effort

    state_interfaces:
      - position
      - velocity

    open_loop_control: True

joint_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController

    joints:
      - joint_lift
      - joint_wrist_pitch
      - joint_wrist_roll
      - joint_wrist_yaw
      - joint_head_pan
      - joint_head_tilt
      - joint_gripper_slide
    
    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: "joint_left_wheel"
    right_wheel_names: "joint_right_wheel"

    wheel_separation: 0.3 # estimate! (340mm - 2x20mm wheel width)
    wheels_per_side: 1
    wheel_radius: 0.05

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    use_stamped_vel: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits, should match MoveIt's default_joint_limits.yaml
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.42
    linear.x.max_acceleration: 0.2
    linear.x.max_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.42
    angular.z.max_acceleration: 0.2
    angular.z.max_jerk: 0.0